### ISSUE TITLE
Incompatible with react 17.0.2

### ISSUE THREAD

**Issue by SunnyAureliusRichard** [HarshRohila/react-custom-events#10]
Hi,

Can the dependency for react be updated?

Getting the following:

    PS web> npm i react-custom-events
    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE unable to resolve dependency tree
    npm ERR! 
    npm ERR! While resolving: undefined@undefined      
    npm ERR! Found: react@17.0.2
    npm ERR! node_modules/react
    npm ERR!   react@"17.0.2" from the root project
    npm ERR!
    npm ERR! Could not resolve dependency:
    npm ERR! peer react@"^16.8.0" from react-custom-events@1.0.5
    npm ERR! node_modules/react-custom-events
    npm ERR!   react-custom-events@"*" from the root project
    npm ERR!
    npm ERR! Fix the upstream dependency conflict, or retry
    npm ERR! this command with --force, or --legacy-peer-deps
    npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
    npm ERR!
    npm ERR! See eresolve-report.txt for a full report.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     2022-03-01T21_09_45_775Z-debug-0.log

Thanks!

**Comment by HarshRohila** [comment]
Thanks for raising this issue, released a new version fixing this

**Comment by kwiat1990** [comment]
@HarshRohila hey in the meantime the very same error occurs with the newest react version (I use v18.0.0).
