### ISSUE TITLE
does not support SSR (server side rendering)

### ISSUE THREAD

**Issue by sergiuchuckmisha** [HarshRohila/react-custom-events#13]
as far as you use `document` in your code, your package will not work with server side rendering

**Comment by HarshRohila** [comment]
Any ideas about fixing that? Or maybe raise PR if possible

**Comment by Ablomis** [comment]
I'm using this custom hook with SSR and it looks like it works:
```
 useEffect(() => {
        const handleEvent = (event: CustomEvent | Event) => {
            const data = (event as CustomEvent).detail;
            eventHandler(data);
        };
        document.addEventListener('nftDataEvent', handleEvent, false);

        return () => {
            document.removeEventListener('nftDataEvent', handleEvent, false);
        };
    });
```
pure document instead of getting element

**Comment by HarshRohila** [comment]
@Ablomis looks like document is available in useEffect, I updated package to lazily use document, instead of using it on import
