### ISSUE TITLE
Consuming event by direct ancestor only

### ISSUE THREAD

**Issue by jkavalec** [HarshRohila/react-custom-events#15]
Is there any way to send event only to direct ancestors?

For instance, I have tab component and tab sends, 'tab-changed' event, the issue is that all tab components catch the event and change tab, while I need this to happen only on tabs component containing tab that generated the event.

Any way how to do this?

**Comment by HarshRohila** [comment]
For this, need to fire a custom event on the child element(and allow bubbling), so only the ancestor elements can catch.

Currently, this library does not allow setting element for firing events, as that will limit the listener to ancestor elements. This library is meant to send events anywhere.

But your use case looks like a good use case for adding an additional feature, I am thinking of adding an API `bubbleEvent` which can support this

You can refer this for firing custom event on an element https://javascript.info/dispatch-events

**Comment by HarshRohila** [comment]
I added new feature for this, checkout "Event Bubbling" section in README
