### ISSUE TITLE
Incorrect state in useCustomEventListener hook

### ISSUE THREAD

**Issue by ryan-nauman** [HarshRohila/react-custom-events#17]
This issue started with release 1.0.9. My state variables in my custom hook are always the value they are initialized at within `useCustomEventListener`. 

In the code below, `orderId` is null in `useCustomEventListener` even when the flow in the hook logs 123 first. 1.0.8 and earlier do not have this issue.

```
function myCustomHook(params) {
  const [orderId, setOrderId] = useState(null);
...
  console.log('orderid', orderId); // outputs 123
  useCustomEventListener(events.receivedOrderStatus, (data) => {
    console.log('orderid', orderId); // outputs null
  });
  useEffect(() => {
    console.log('orderid', orderId); // outputs 123
    setOrderId(params.orderId);
  }, [params.orderPlacementTimestamp]);
}
```

**Comment by HarshRohila** [comment]
Thanks for raising the issue.
Recently I did the change to run `useCustomEventListener` hook once, instead of adding and removing listener on every render.
It looks like, `useCustomEventListener` need to support dependency array parameter (like `useEffect`)

**Comment by HarshRohila** [comment]
Released new version to fix this, updated documentation
