### ISSUE TITLE
feature request: error handler

### ISSUE THREAD

**Issue by foadabdollahi** [HarshRohila/react-custom-events#8]
feature request: if add error handler function that show some error happened is better.

```
 useCustomEventListener('Send massage', message => {
     throw new Error('Something bad happened.');
     });
```

something like it:
`   emitCustomEvent('Send massage', message, function success(){}, function error(err){ });`

thanks for your useful package :)

**Comment by HarshRohila** [comment]
do you mean when an error is thrown in the `useCustomEventListener` side, it will call the error callback at the `emitCustomEvent` side?
if yes, this can be achieved with current functionality by having success and error callback as part of the message

```
const eventObj= {
  message,
  success() {},
  error(err) {}
}
emitCustomEvent('Send massage', eventObj)

useCustomEventListener(('Send massage', eventObj => {
  eventObj.error(new Error('Something bad happened.'))
}
```
